version: '3.7'
services:
  database:
    container_name: notejam_db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: notejam
    networks:
     notejam_net:
      aliases:
       - database
  notejam:
    build:
     context: ./notejam
     network: docker_notejam_net
     args:
      - SYMFONY_ENV=prod
      - SYMFONY__DATABASE__DRIVER=pdo_mysql
      - SYMFONY__DATABASE__HOST=database
      - SYMFONY__DATABASE__PORT=3306
      - SYMFONY__DATABASE__NAME=notejam
      - SYMFONY__DATABASE__USER=root
      - SYMFONY__DATABASE__PASSWORD=example
    depends_on:
      - database
    container_name: notejam_php
    ports:
     - "8080:80"
    restart: always
    environment:
      SYMFONY_ENV: prod
      SYMFONY__DATABASE__DRIVER: pdo_mysql
      SYMFONY__DATABASE__HOST: database
      SYMFONY__DATABASE__PORT: 3306
      SYMFONY__DATABASE__NAME: notejam
      SYMFONY__DATABASE__USER: root
      SYMFONY__DATABASE__PASSWORD: example
    tty: true
    image: notejam
    networks:
     notejam_net:
      aliases:
       - notejam
networks:
  notejam_net:
    driver: bridge
